# link = https://www.geeksforgeeks.org/vector-space/

# NOte(kurang apa/sisa apa?)

# TO-Do

# Output

# QNA
1.buktikan terkait ini:

Masalah kata yang tidak ada dalam kosakata (Out of Vocabulary): Ketika ada kata baru yang tidak ada dalam kosakata yang telah dipelajari, One-Hot Encoding tidak bisa memberikan representasi yang bermakna untuk kata tersebut. Ini disebut masalah "Out of Vocabulary" dan dapat menyebabkan kesulitan dalam memahami atau memproses teks baru yang akan menghasilkan prediksi kata yang tidak akurat.
disertai code studi casenya!
: cek: https://chatgpt.com/c/67009936-9b24-8009-94a0-55c29778c327
2. buktikan terkait ini:
Tidak ada representasi panjang yang tetap: Meskipun One-Hot Encoding menghasilkan vektor yang panjangnya tetap untuk setiap kata, masalah muncul ketika kita mencoba untuk mewakili seluruh kalimat atau dokumen. Tidak ada panjang tetap untuk representasi teks yang lebih panjang, sehingga menyulitkan untuk menggabungkan atau membandingkan teks dengan panjang yang berbeda.

 disertai code studi casenya! cek: https://chatgpt.com/c/67009936-9b24-8009-94a0-55c29778c327

3. lalu one hot encoding sangat cocok dalam hal apa untuk digunakan?:  cek: https://chatgpt.com/c/67009936-9b24-8009-94a0-55c29778c327

# istilah/complex
1. cosine similarity
2. vector space model

# Code practical: label and One Hot Encoding
1. Ini adalah pendekatan lama yang sudah jarang dipakai. jadi tidak perlu dipelajari secara keseluruhan, tapi paham aja konsepnya.
2. Ada 4 alasan yang ngebuat ini sudah tidak layak dipakai:
* . **Kata-kata yang mirip tidak memiliki representasi yang mirip**: Dalam One-Hot Encoding, setiap kata diwakili oleh vektor yang hanya memiliki satu elemen dengan nilai 1, sementara yang lainnya 0. Ini berarti kata-kata yang secara semantik mirip (misalnya, "kucing" dan "anjing") tidak memiliki representasi vektor yang mirip. Ini bisa menjadi masalah karena algoritma pembelajaran mesin tidak bisa menangkap hubungan antara kata-kata yang sebenarnya memiliki makna yang mirip.

*  **Masalah kata yang tidak ada dalam kosakata (Out of Vocabulary)**: Ketika ada kata baru yang tidak ada dalam kosakata yang telah dipelajari, One-Hot Encoding tidak bisa memberikan representasi yang bermakna untuk kata tersebut. Ini disebut masalah "Out of Vocabulary" dan dapat menyebabkan kesulitan dalam memahami atau memproses teks baru yang akan menghasilkan prediksi kata yang tidak akurat.

* **Tidak ada representasi panjang yang tetap**: Meskipun One-Hot Encoding menghasilkan vektor yang panjangnya tetap untuk setiap kata, masalah muncul ketika kita mencoba untuk mewakili seluruh kalimat atau dokumen. Tidak ada panjang tetap untuk representasi teks yang lebih panjang, sehingga menyulitkan untuk menggabungkan atau membandingkan teks dengan panjang yang berbeda.

* **Mengonsumsi terlalu banyak memori**: Karena One-Hot Encoding menghasilkan vektor yang sangat panjang, terutama jika kosakata besar, ini mengonsumsi banyak memori. Jika kata yang diwakili berada di akhir daftar vektor, maka banyak elemen dalam vektor yang akan tetap 0, dan hanya satu elemen yang akan 1. Hal ini menyebabkan kompleksitas waktu yang buruk, terutama saat mengelola kosakata yang besar.


**Versi pakai sklearn**

In [ ]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder

# Input data
S1 = 'dog bites man'
S2 = 'man bites dog'
S3 = 'dog eats meat'
S4 = 'man eats food'

data = [S1.split(), S2.split(), S3.split(), S4.split()]
flattened_data = sum(data, [])
print(flattened_data)
# Reshape the data into a 2D array for OneHotEncoder
# Convert the list to a NumPy array first
flattened_data_array = np.array(flattened_data)
# Reshape the array to 2D if necessary
onehot_encoder = OneHotEncoder()
onehot_encoded = onehot_encoder.fit_transform(flattened_data_array.reshape(-1, 1)).toarray()
print("Onehot Encoded Matrix:\n", onehot_encoded)

['dog', 'bites', 'man', 'man', 'bites', 'dog', 'dog', 'eats', 'meat', 'man', 'eats', 'food']
['dog' 'bites' 'man' 'man' 'bites' 'dog' 'dog' 'eats' 'meat' 'man' 'eats'
 'food']
Onehot Encoded Matrix:
 [[0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]


In [1]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

# Input data
S1 = 'dog bites man'
S2 = 'man bites dog'
S3 = 'dog eats meat'
S4 = 'man eats food'
data = [S1.split(), S2.split(), S3.split(), S4.split()]
values = data[0]+data[1]+data[2]+data[3]
print("The data: ",values)

#Label Encoding
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print("Label Encoded:",integer_encoded)

#One-Hot Encoding
onehot_encoder = OneHotEncoder()
onehot_encoded = onehot_encoder.fit_transform(data).toarray()
print("Onehot Encoded Matrix:\n",onehot_encoded)

The data:  ['dog', 'bites', 'man', 'man', 'bites', 'dog', 'dog', 'eats', 'meat', 'man', 'eats', 'food']
Label Encoded: [1 0 4 4 0 1 1 2 5 4 2 3]
Onehot Encoded Matrix:
 [[1. 0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 1. 0. 1. 0. 0. 0.]
 [1. 0. 0. 1. 0. 0. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 0.]]


**Versi pakai manual**

In [1]:
# membuat assign value
documents = ["bites dog eats.", "food bites dog.", "Dog eats man.", "Man eats meat."]
processed_docs = [doc.lower().replace(".","") for doc in documents]
processed_docs

['bites dog eats', 'food bites dog', 'dog eats man', 'man eats meat']

In [5]:
#Build the vocabulary
vocab = {}
count = 0
for doc in processed_docs:
    for word in doc.split():
        if word not in vocab:
            count = count +1
            vocab[word] = count #kata uniq adalah koentci
            # vocab[count] = word #ini tidak cocok karena komputer akan mengeluarkan output urutan berdasarkan jumlah kata bukan yang dimaksud kondisi
print(vocab)

{'bites': 1, 'dog': 2, 'eats': 3, 'food': 4, 'man': 5, 'meat': 6}


In [6]:
#Get one hot representation for any string based on this vocabulary.
#If the word exists in the vocabulary, its representation is returned.
#If not, a list of zeroes is returned for that word.
def get_onehot_vector(somestring):
    onehot_encoded = []
    for word in somestring:
        temp = [0]*len(vocab)
        if word in vocab:
            temp[vocab[word]-1] = 1 # -1 is to take care of the fact indexing in array starts from 0 and not 1
        onehot_encoded.append(temp)
    return onehot_encoded

In [7]:
# Input data
S1 = 'dog bites man'
S2 = 'man bites dog'
S3 = 'dog eats meat'
S4 = 'man eats food'
data = [S1.split(), S2.split(), S3.split(), S4.split()]
flattened_data = sum(data, [])
print(flattened_data)
get_onehot_vector(flattened_data)

['dog', 'bites', 'man', 'man', 'bites', 'dog', 'dog', 'eats', 'meat', 'man', 'eats', 'food']


[[0, 1, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 1, 0],
 [1, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 1, 0],
 [0, 0, 1, 0, 0, 0],
 [0, 0, 0, 1, 0, 0]]

In [ ]:
# code manual versi 2
# Dokumen pelatihan
train_documents = ["cat eats fish", "dog bites man", "man eats meat"]

# Pra-pemrosesan: Lowercase dan split kata
processed_train_docs = [doc.lower().split() for doc in train_documents]

# Membangun kosakata dari dokumen pelatihan
vocab = {}
count = 0
for doc in processed_train_docs:
    for word in doc:
        if word not in vocab:
            count += 1
            vocab[word] = count

print("Kosakata yang dihasilkan dari dokumen pelatihan:")
print(vocab)

# Fungsi One-Hot Encoding berdasarkan kosakata yang sudah dibangun
def one_hot_encode(document, vocab):
    encoding = []
    for word in document.split():
        if word in vocab:
            one_hot_vector = [0] * len(vocab)
            one_hot_vector[vocab[word] - 1] = 1
            encoding.append(one_hot_vector)
        else:
            # Jika kata tidak ada di kosakata, tidak bisa di-encode
            print(f"Kata '{word}' tidak ada dalam kosakata (OOV)")
            encoding.append([0] * len(vocab))  # Representasi 0 untuk OOV
    return encoding

# Dokumen baru yang akan diuji (mengandung kata OOV)
new_document = "cat bites fish man lion"

# Encoding dokumen baru
print("\nEncoding untuk dokumen baru:")
encoded_new_doc = one_hot_encode(new_document, vocab)
for word, encoding in zip(new_document.split(), encoded_new_doc):
    print(f"'{word}' => {encoding}")


**CODE LENGKAP**
1. cek: https://github.com/practical-nlp/practical-nlp-code/blob/master/Ch3/01_OneHotEncoding.ipynb
2. penjelasan ulikan: https://chatgpt.com/c/c3078b57-fd8d-4774-bb70-ca3aea1b7fd7
3.