<a href="https://colab.research.google.com/github/Symphoen1x/LearnAI-NLP/blob/main/Numpy/BasicNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# All About Learning
1. gw ga bakalan nulis/duplikat semua, tapi gw bakalan fokus buat percobaan, catatan yang blm ada di sumber, latihan, curiousty.

# TO-Do
1. next, ngejar 2 bagian tersisa buat basic numpy https://www.w3schools.com/python/numpy/numpy_array_sort.asp

# Note
* fokus gw sekarang langsung di w3schoold karena dia punya roadmap lumayan fokus ke tujuan gw + ramah enginer https://www.w3schools.com/python/numpy/

# Source:
1. Buku mastering Python for Data Science
2. Think stats
3. cek cheatset ada di folder math bagian onedrive
3. https://www.w3schools.com/python/numpy/trypython.asp?filename=demo_numpy_random_distribution1

# Creating an array

In [ ]:
# import library
import numpy as np

In [ ]:
# Perkalian dan dot product
a1 = np.array([[1, 2], [2, 4]])
a2 = np.array([[0, 1], [1, 0]])
print("Perkailan")
print(a1 * a2)
print("Dot product")
np.dot(a1, a2)

Perkailan
[[0 2]
 [2 0]]
Dot product


array([[2, 1],
       [4, 2]])

In [ ]:
# Creation function
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [ ]:
np.fliplr(np.diag([1, 2, 3]))


array([[0, 0, 1],
       [0, 2, 0],
       [3, 0, 0]])

In [ ]:
np.vander((1, 2, 3, 4), 3)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1]])

In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
b = a[:2]
b += 1
print('a =', a, '; b =', b)

a = [2 3 3 4 5 6] ; b = [2 3]


In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
b = a[:2].copy()
b += 1
print('a =', a, '; b =', b)

a = [1 2 3 4 5 6] ; b = [2 3]


# Basic indexing

## Pengindex-an elemen tunggal

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x.shape = (2, 5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Note for more easy understanding
1. cara pertama di bawah tidak efisien dari cara kedua. Alasanya Pada x[0][2], Python terlebih dahulu menghasilkan array baru untuk baris ke-0 sebelum akhirnya mengambil elemen ke-2, jadi ada dua langkah dan penggunaan memori ekstra untuk array sementara.
Pada x[0, 2], Python langsung mengakses elemen yang diinginkan tanpa menghasilkan array sementara, sehingga lebih cepat dan efisien.

In [ ]:
#tidak efisien
x[0][2]

2

In [ ]:
x[0, 2]

2

In [ ]:
# pembuktikan apakah cara pertama benar-benar menyisakan array sementara: https://chatgpt.com/c/66eb276d-b3e0-800b-beff-f288ab3eaa56
import numpy as np

# Buat array NumPy 2D
x = np.array([[1, 2, 3], [4, 5, 6]])

# Cara pertama: x[0, 2] - langsung mengakses elemen
print("x[0, 2]:", x[0, 2])
print("Tipe dari x[0, 2]:", type(x[0, 2]))

# Cara kedua: x[0][2] - dua langkah pengindeksan
print("x[0][2]:", x[0][2])
print("Tipe dari x[0]:", type(x[0]))  # Ini akan menghasilkan array sementara (baris pertama)
print("Tipe dari x[0][2]:", type(x[0][2]))  # Setelah pengambilan elemen dari array sementara


x[0, 2]: 3
Tipe dari x[0, 2]: <class 'numpy.int64'>
x[0][2]: 3
Tipe dari x[0]: <class 'numpy.ndarray'>
Tipe dari x[0][2]: <class 'numpy.int64'>


In [ ]:
# Cara kedua: x[0][2] - dua langkah pengindeksan
print("x[1][2]:", x[1][2])
print("Tipe dari x[1]:", type(x[1]))  # Ini akan menghasilkan array sementara (baris pertama)
print("Tipe dari x[1][2]:", type(x[1][2]))  # Setelah pengambilan elemen dari array sementara


x[1][2]: 6
Tipe dari x[1]: <class 'numpy.ndarray'>
Tipe dari x[1][2]: <class 'numpy.int64'>


## Qna
1. So note that x[0, 2] == x[0][2] though the second case is more inefficient as a new temporary array is created after the first index that is subsequently indexed by 2.

maksudnya bagaimana? jelaskan dong!
2. coba buktikan keefisienya dari data memori! prompt[ini outputnya apa?]
2. bagaimana cara membuktikan bahwa ada array sementara dan tidak?
3. x[0, 2]: 3
Tipe dari x[0, 2]: <class 'numpy.int64'>
x[0][2]: 3
Tipe dari x[0]: <class 'numpy.ndarray'>
Tipe dari x[0][2]: <class 'numpy.int64'>
di atas adalah hasilnya, memang terlihat benar bahwa ada memori sementara. tapi saya sedikit bingung kenapa jenisnya beda? yang pembuktian kedua awalnya dia bertipe Tipe dari x[0]: <class 'numpy.ndarray'> dan kedua bertipe Tipe dari x[0][2]: <class 'numpy.int64'>
4. jika array bertipe <class 'numpy.int64'> adalah indikasi array tunggal, maka tipe <class 'numpy.int32'> untuk apa?

# slicing dan striding(mengiris dan melangkah)

## Note for more easy understanding
1.

## Qna
1. Kasus pengindeksan paling sederhana dengan bilangan bulat N mengembalikan skalar array yang mewakili item yang sesuai. Seperti dalam Python, semua indeks berbasis nol: untuk indeks ke- i
, rentang yang valid adalah
Di mana
adalah elemen ke-i dari bentuk array. Indeks negatif diartikan sebagai penghitungan dari akhir array ( misalnya , jika
, itu berarti
).


tolong jelaskan secara lebih mudah di pahami maksud text diatas!
2. biasanya ada yang mengdenotasikan rentang valid adalah 0 < ni < di. dimana di adalah elemen ke-i dari bentuk array. maksudnya di ini lebih jelasnya gimana ya?
3. ada yang mengatakan bahwa indeks negatif diartiken sebagai penghitungan dari akhir array, misalnya jika ni < 0, itu artinya ni+di. tolong buktikan maksudnya!
4. Sintaks irisan dasar adalah i:j:kdi mana i adalah indeks awal, j adalah indeks akhir, dan k adalah langkah (k tidak boleh sama dengan 0
). Ini memilih elemen m (dalam dimensi yang sesuai) dengan nilai indeks i , i + k , …, i + (m - 1) k di mana  m = q + (r tidak sama dengan 0)  
dan q dan r adalah hasil bagi dan sisa yang diperoleh dengan membagi j - i dengan k : j - i = qk + r , sehingga i + (m - 1) k < j .


jelaskan maksud di atas!
5. tolong berikan contoh perhitungan rumus-rumus tersebut dong tertama yang  i + (m - 1) k dan  m=q+(r tdk boleh = 0)!
6. total elemen di dalamnya adalah genap. bagaimanaa jika totalnya ganjil? apakah rumus:  m = q + (r ≠ 0) tetap berlaku?

## practical and evidence

In [ ]:
import numpy as np
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
p = x[1:9:2]
print(x)
print(p)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7]


In [ ]:
# by scratch slicing with rekursif
def recursive_slice(arr, i, j, k, result=None):
    # Jika result tidak diberikan, inisialisasi dengan list kosong
    if result is None:
        result = []

    # Basis rekursi: jika indeks i sudah mencapai atau melewati j, berhenti
    if i >= j:
        return result

    # Tambahkan elemen saat ini ke dalam hasil
    result.append(arr[i])

    # Panggil rekursif dengan langkah k
    return recursive_slice(arr, i + k, j, k, result)

# Contoh penggunaan
arr = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
result = recursive_slice(arr, 1, 9, 2)
print(result)  # Output: [1, 3, 5, 7]


[1, 3, 5, 7]


# reshape

## Ilmu baru
* -1 itu adalah suatu value dalam reshape yang jika lu bingung buat ngisi diantara value yang berkaitan dengan dimensi, lu bisa isi -1 sebagai nilai automatisnya. cuma dia itu hanya bisa dipakai sekali dalam value method reshape dan bebas di dimensi mana aja!

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(-1, 2, 2)




[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Iteration in numpy

## ilmu baru
* sebetulnya ini harusnya di awal, tapi nemu di sini jadi gpp
* jika menemukan tanda (:) aja dalam value index/slicing/looping/dll, itu artinya rujukan untuk semua elemen pada suatu dimensi(dalam contoh itu dim 1)
* Kalo method .nditer() itu kayak cheat buat lu ngerubah complex aray/matrix/tensor jadi sebuah elemen satuan.

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
# arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr[:, ::2]):
  print(x)

# Join

## ilmu baru
1. jika ada parameter axis dalam method concatenate, terdapat dua value. 1 untuk pemformatan baris dan 0 untuk pemformatan kolom pada mode mergenya. cara mahaminya gini, kalo yang 1 itu kayak lu pas nambahin sebuah elemen dalam array suatu dimensi ke  array lain yang dimensinya sama dari atas sehingga mau ga mau elemen di kedua array harus masuk menjadi 1 array dimensi yang sama. sementara, kalo 0 itu kayak ketika ada suatu array dimensi tertentu masuk ke array dimensi di atas yang sejenis, tapi dia kayak menumpuk lewatnya samping dan kayak nambah baris baru di bawahnya sehingga tidak terjadi penggabungan secara array sejenis.

secara intuitif 1: tumpukan kedalaman ke sebuah kolom, 0: kolom

2.  jika ada parameter axis dalam method concatenate, terdapat dua value. 1 untuk pemformatan kolom dan 0 untuk pemformatan baris pada mode penumpukanya.Jadi kalo value 1 itu ketika ada dua array dengan jenis dimensi yang sama, array pertama akan menumpuk array lain dengan cara merapikan setiap elemennya dala suatu array dimensi diluarnya lalu menggabungkan nilai value kedua array seperti mengambil suatu array atas dan bawah per elemenya ke dalam sebuah array baru. setiap array baru tadi ditumpuk kembali ke mode susunan baris urut.sementara yang value 0 hanya seperti menumpuk array satu dan dua tanpa adanya penggabungan per elemen keduanya.


secara intuitif 1: 0: tumpukan baris ke sebuah kolom,1: per elemen array pertama -> tumpuk per elemen array kedua sebaris (kedalaman) dikumpulkan dalam suatu dalam satu kolom

In [ ]:
# 1
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

colmerge = np.concatenate((arr1, arr2), axis=1)
rowmerge = np.concatenate((arr1, arr2), axis=0)

print(colmerge)
print(rowmerge)


[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
# 2
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])

arr2 = np.array([[7, 8, 9], [10, 11, 12]])

arr = np.stack((arr1, arr2), axis=1)
# arr = np.stack((arr1, arr2), axis=0)


print(arr)


[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]


## QnA
1. apakah dalam array join tidak bisa melakukan join beberapa array dengan dimensi yang berbeda-beda? https://chatgpt.com/c/66ee6581-9eb8-800b-84c9-8ab39c0e8964

# spliting array in numpy

## Ilmu baru non w3school penjelasanya
1. asumsikan hstack() itu kayak lu lagi mau misahin 3 bagian uniq yang berbeda layaknya bentuk matrix, tapi diambil jadi potongan-potongan baru yang  masing-masing potongan itu isinya 3 bagian yang berbeda. sementara kalo hsplit() itu kayak lu mau nggabungin 3 bagian dalam satu wadah tanpa harus memisahkan secara vertikal sebuah bagian matrix

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

# newarr = np.hstack(arr) #karena jadi satu maka ga bisa dicustomize aturan lain
newarr = np.hsplit(arr, 3) #karena jadi potongan baru maka bisa tuh diatur  berapa persen tiap isi potongan ada bagain-bagian uniqnya


print(newarr)


## QNA
1. buatlah semacam analogi sederhana untuk membedakan hstack yang diambil secara horizontal dengan hsplit yang diambil secara vertikal! https://chatgpt.com/c/66f262ed-4008-800b-b6d5-1f3b6b5bea82

# Searching Arrays

## Ilmu baru out of w3school penjelasanya
*  1. import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x) kenapa  code tersebut outputnya adalah 1,2,3? bagaimana bisa?

jawaban singkatnya: jadi input per elemen dalam array yang diguanakan searching array ini menggunakan perulangan binary yang setiap elemen adalah percobaan terpisah yang berarti jika ada 3 elemen maka elemen 1 dan lainya bekerja independen dalam suatu algoritma binary. intinya, beda dengan perulangan biasa  yang langsung menentuka secara holistik letak kemungkinan masing-masing elemen yang menjadi input dalam suatu array.
pembuktianya ya tentu dengan mencoba menggunakan elemen di luar batas misal:

In [1]:
import numpy as np

arr = np.array([1, 3, 5, 7])

# x = np.searchsorted(arr, [2, 4, 6])
x = np.searchsorted(arr, [8, 9, 10]) #jika penggunaan perulangan binary seperti penjelasan di atas benar, maka output dari input ini akan sama karena masing-masing diproses secara independen

print(x)

[4 4 4]
