<a href="https://colab.research.google.com/github/Symphoen1x/LearnAI-NLP/blob/main/Numpy/BasicNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# All About Learning
1. gw ga bakalan nulis/duplikat semua, tapi gw bakalan fokus buat percobaan, catatan yang blm ada di sumber, latihan, curiousty.

# QNA

# Note
1. besok lanjutin tutroial di web: https://numpy.org/devdocs/user/basics.indexing.html yang indexing ke atas

# complex(boleh insert link kok)

# Source:
1. Buku mastering Python for Data Science
2. Think stats
3. https://numpy.org/devdocs/user/basics.creation.html

# Creating an array

In [1]:
# import library
import numpy as np

In [4]:
# Perkalian dan dot product
a1 = np.array([[1, 2], [2, 4]])
a2 = np.array([[0, 1], [1, 0]])
print("Perkailan")
print(a1 * a2)
print("Dot product")
np.dot(a1, a2)

Perkailan
[[0 2]
 [2 0]]
Dot product


array([[2, 1],
       [4, 2]])

In [11]:
# Creation function
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [9]:
np.fliplr(np.diag([1, 2, 3]))


array([[0, 0, 1],
       [0, 2, 0],
       [3, 0, 0]])

In [14]:
np.vander((1, 2, 3, 4), 3)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1]])

In [19]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
b = a[:2]
b += 1
print('a =', a, '; b =', b)

a = [2 3 3 4 5 6] ; b = [2 3]
